### PR TITLE
Add Prior Art Section

### PR DESCRIPTION
**Pull request by WebReflection**
As suggested in PR #12 it could be interesting
to investigate or share code and knowledge
about CommonJS in ESM and/or vice-versa

### CODE REVIEW

**Comment by benjamn** [comment]
Would https://github.com/benjamn/reify and https://github.com/standard-things/esm fall into this category?

**Comment by WebReflection** [comment]
mind providing same format w/ quick description per project?

**Comment by benjamn** [comment]
Added some more details, hopefully not too much!

**Comment by WebReflection** [comment]
you wrote `@std/esm` as link instead of @std/esm (backtics)

**Comment by WebReflection** [comment]
thanks @benjamn, we overlapped a little bit so I've cleaned up all changes into a single squashed commit

**Comment by jdalton** [comment]
Hi! I just `watch`ed this repo so I should get notifications on activity. Thanks for the ping in @benjamn via https://github.com/nodejs/modules/commit/4d0385c4b6c8a36e6674f03a93f1d3ffd8e29f0d. If we're to help differentiate between `@std/esm` and reify it would be:
> `@std/esm` is a fork of Reify focused on following Node's ESM support roadmap while providing a bridge from the CJS/ESM usage of today to the ESM of tomorrow.

**Comment by WebReflection** [comment]
@jdalton done

**Comment by WebReflection** [comment]
maybe I miss something but what has Babel to do with modules?

**Comment by bmeck** [comment]
@WebReflection I'm not sure we should exclude things just because they solve multiple use cases.

**Comment by MylesBorins** [comment]
@WebReflection I think that babel is useful to include as many modules were authored based on the way the module loader worked (shim of require)

**Comment by bmeck** [comment]
We should probably also consider Webpack since it also implements a module loader entirely separate from Babel if we include babel. Traceur might also be related since it has a way of compiling down. Are there any AMD based solutions that I'm missing (I'm not as well versed in AMD solutions)?

**Comment by DanielRosenwasser** [comment]
TypeScript also provides interop strategy that basically treats a `module.exports` and namespace object as 1:1. It also more or less implements the Babel/Webpack strategy as of 2.7.

**Comment by WebReflection** [comment]
> We should probably also consider Webpack ...

that's what I was talking about ... then rollup, all my offline and runtime utilities, then parcel ... then ...

**Comment by bmeck** [comment]
@WebReflection yup, all are prior art. I have plenty of tools as well.

**Comment by benjamn** [comment]
Babel and TypeScript are both used by server-side applications in Node, whereas client-side bundlers like Webpack are less relevant for this working group, since it's not common to run a Webpack bundle in Node, so there's not much Node-specific insight to take from Webpack.

**Comment by weswigham** [comment]
@WebReflection In many ways, es modules as presented by [babel](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/), [webpack](https://webpack.js.org/concepts/modules/), [rollup](https://github.com/rollup/rollup) and [systemjs](https://github.com/systemjs/systemjs), or [typescript](https://www.typescriptlang.org/docs/handbook/modules.html), are some of the most widely used forms of them in use today. It'd be a big omission to elide them. Plus, it's a list of links, what can it hurt.

**Comment by WebReflection** [comment]
I actually agree with @benjamn and I have no budget (in terms of time) to change this PR per each person that wrote a browser side module solver ... can we stick with just Babel and TypeScript as more Node relevant?

**Comment by DanielRosenwasser** [comment]
> so there's not much Node-specific insight to take from Webpack.

Webpack provides an interoperability strategy to consume CommonJS modules with ES module syntax, and specially operates on ES-module-authored CommonJS modules, much like the other tools here. so I'm not sure why you wouldn't want to account for it.

**Comment by bmeck** [comment]
@WebReflection I request Webpack not be avoided, it is one of the largest tools used by the node ecosystem and also is able to [target Node](https://webpack.js.org/concepts/targets/#usage).

**Comment by WebReflection** [comment]
Split in sections with all the famous bundlers included.

**Comment by WebReflection** [comment]
I think Myles is busy now, I'll do it since there are 2 approvals.

**Pull request merged**
