### PR TITLE
fix: add members missed by ncu-team to team list

### PR DESCRIPTION
**Pull request by DerekNonGeneric**
This PR adds members missed by the `ncu-team` tool to the team list.

### CODE REVIEW

**Comment by DerekNonGeneric** [comment]
So far, I am only aware of myself, likely due to recent team re-shuffling, but I would like to continue being pinged on these issues once that gets sorted out in a couple of weeks.


/cc @Trott

**Comment by jasnell** [comment]
@DerekNonGeneric ... There has not been "team reshuffling". The TSC has removed you from the org and therefore all teams for the reasons that have been communicated to you in email.

**Comment by DerekNonGeneric** [comment]
@jasnell, the part about seeking a resolution that I inquired about in my email to the TSC went completely ignored, so I assumed this was supposed to be a temporary reshuffling otherwise, you wouldn't see me contributing to Node.js anymore as I would have no business being in this issue tracker or any Node.js issue trackers for that matter.

**Comment by DerekNonGeneric** [comment]
I just remembered that the modules team was sunsetted, so never mind.

**Pull request closed without merging**
