### PR TITLE
Add tzmanics as an observer

### PR DESCRIPTION
**Pull request by tzmanics**
Hoping to help where I can 👍

### CODE REVIEW

**Comment by benjamingr** [comment]
Hi @tzmanics 👋 

Care to add some information about your background and why you're interested in being an observer? 

Purely asking for my own interest (hope that's OK) - not as a part of some process :)

**Comment by jdalton** [comment]
@MylesBorins I believe there may be some follow-up needed for various script hooks or processes. If so this is just an FYI note for that.

**Comment by benjamingr** [comment]
Welcome on board @tzmanics ! 🎉

**Comment by tzmanics** [comment]
Thanks so much @benjamingr! Can't wait to learn as much as possible to see the best way to help!

**Pull request merged**
