### PR TITLE
doc: s/Google Hangouts/Zoom

### PR DESCRIPTION
**Pull request by MylesBorins**
Corrected detail about where we host meetings.

### CODE REVIEW

**Comment by benjamingr** [comment]
I have to say that while I prefer hangouts in general - Zoom worked really well for it and I'm +1 on using it for the meetings.

**Comment by benjamingr** [comment]
IMO this doesn't need to wait the 2 weeks for meeting consensus

**Comment by MylesBorins** [comment]
@benjamingr this should not have been merged. The current policy is that we need to approve PRs in a meet to land. Please revert

**Comment by benjamingr** [comment]
@MylesBorins reverted.

**Comment by MylesBorins** [comment]
thanks @benjamingr I'll open another PR

**Pull request merged**
