### PR TITLE
Add Doron Tsur as observer

### PR DESCRIPTION
**Pull request by qballer**
I would like to participate in the module group meetings.
I'm interested in the ESM specification and the emerging import map standard.

### CODE REVIEW

**Comment by qballer** [comment]
cc: @guybedford

**Comment by MylesBorins** [comment]
please don't land this until @qballer has been added to the team on github

**Comment by qballer** [comment]
is there anything I should be doing on my side ?

**Comment by DerekNonGeneric** [comment]
I'm just an Observer otherwise I might've done what's needed to get this merged.

**Comment by MylesBorins** [comment]
Based on the governance we need a meeting with quorum to approve. I'll chase people down next week to get approvals

**Pull request merged**
