### PR TITLE
Consistent last name formatting 

### PR DESCRIPTION
**Pull request by xtuc**
Sorry it's a French thing, it's looking inconsistent/weird.

### CODE REVIEW

**Comment by xtuc** [comment]
@devsnek how could I update the node-core-utils?

**Comment by ljharb** [comment]
Wouldn’t it read it from @xtuc’s Github profile, which has his last name currently not in all caps?

**Comment by targos** [comment]
It uses GitHub's GraphQL API, that returns the following:

```json
{
  "data": {
    "user": {
      "login": "xtuc",
      "name": "Sven Sauleau"
    }
  }
}
```

It looks like @xtuc updated his GH profile, so this PR LGTM.

**Comment by xtuc** [comment]
Yes, I've updated my profile since then. Should we close this PR and run an update of the team list?

**Pull request merged**
